- name: Download the tarball
  get_url: url="http://{{ apache_mirror }}/kafka/{{ kafka_version }}/kafka_2.11-{{ kafka_version }}.tgz" dest=/opt/kafka_2.11-{{ kafka_version }}.tgz
- name: Extract the tarball
  unarchive: src=/opt/kafka_2.11-{{ kafka_version }}.tgz dest=/opt/ copy=no creates=/opt/kafka_2.11-{{ kafka_version }}
- name: Symlink install directory
  file: src=/opt/kafka_2.11-{{ kafka_version }} path=/opt/kafka state=link
- name: Set permissions to Kafka folder
  file: path=/opt/kafka/ owner=root group=root recurse=yes
- name: Create Kafka log directory
  file: path={{ kafka_log_dir }} state=directory owner={{ kafka_user }} group={{ kafka_group }}
- name: Link the log directory
  file: src={{ kafka_log_dir }} path=/opt/kafka/logs state=link
- name: run kafka
  shell: |
   cd kafka_2.11-0.11.0.0
   bin/zookeeper-server-start.sh -daemon config/zookeeper.properties
   bin/kafka-server-start.sh -daemon config/server.properties
