
---
 - name: Provision EC2 Instances
   local_action:
     module: ec2
     key_name: "{{ ec2_keypair }}"
     group_id: "{{ ec2_security_group }}"
     instance_type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image }}"
     vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
     region: "{{ ec2_region }}"
     instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
     assign_public_ip: yes
     wait: true
     count: "{{ ec2_instance_numbers }}"
   register: ec2

 - debug: var=item
   with_items: "{{ ec2.instances }}"
 
 - name: Add the newly created EC2 instance(s) to the local host group
   local_action: lineinfile 
                 dest="./hosts" 
                 regexp={{ item.public_ip }} 
                 insertafter="\[{{ hosts_tag }}\]" line={{ item.public_ip }}
   with_items: "{{ ec2.instances }}"

 - name: Wait for the instances to boot by checking the ssh port
   wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
   with_items: "{{ ec2.instances }}"
 - mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.inspectorio@gmail.com
    password: Inspectorio2017
    to: Dang Phong <phong@inspectorio.com>
    subject: Ansible-provisioning-report
    body: "System {{ ec2_provision_tier }} has been successfully provisioned. \n
	EC2 instance {{ec2.instances[0].id}} created on {{ec2.instances[0].public_ip}} \n"
